### ISSUE TITLE
RL Training  Issue

### ISSUE THREAD

**Issue by miayemaw** [harvard-edge/airlearning-rl#1]
Hello Sri,

Here is my git log records as u said.. 

![image](https://user-images.githubusercontent.com/16092809/60878170-2f9c6800-a27a-11e9-8996-acf0a4d1601a.png)

My problem is: 
When i try to test DQN training (airlearning_rl). i did connect but training not start..
I used this one on windows 10, unreal engine 4.18.3..

![image](https://user-images.githubusercontent.com/16092809/60878314-74280380-a27a-11e9-85b3-0b28f0c94015.png)

**Comment by srivatsankrishnan** [comment]
Thanks for opening an issue here. 

So I tried couple of things at my end and I could not reproduce this at my end:

First, I did a git recursive clone from the [airlearning repository](https://github.com/harvard-edge/airlearning). This should pull both UE4 repo and RL repo correctly. Following the instructions provided in the [readme page](https://github.com/harvard-edge/airlearning-rl/tree/dcd8a39f77992873f49b6872aa534a64a2bfa23a) I ran the training script. It seems to start the training for me.

Second, I just git cloned the RL repo separately and went back to the same tag as what you shown on your screen shot. This also seems to run fine at my end.

[Here](https://github.com/srivatsankrishnan/files/blob/master/github_issue.gif) is a GIF with the same commit hash as yours and running fine at my end.

Couple of more questions and suggestions:
1) Did you run the move.py after installing airsim (pip install airsim)?
2) Sometimes I have noticed weird networking issue with AirSim on Windows. After restarting Windows, the networking issue seems to go away. Maybe you can give that a try.

**Comment by miayemaw** [comment]
i run move.py , it worked well
![image](https://user-images.githubusercontent.com/16092809/60980758-0958f400-a370-11e9-8458-25b0f5801f19.png)


but for training it still the same problem.. even after restarting Windows.. (( 

It's possible because of AirSim??

**Comment by miarmoh** [comment]
> i run move.py , it worked well
> ![image](https://user-images.githubusercontent.com/16092809/60967984-eec65100-a356-11e9-8d48-4edecdac1cc5.png)
> 
> but for training it still the same problem.. even after restarting Windows.. ((

**Comment by miayemaw** [comment]
I did found the solution. now RL training is working fine.

![image](https://user-images.githubusercontent.com/16092809/60980797-1f66b480-a370-11e9-9ca5-fca16b04dd60.png)

I updated on the machine_dependent_settings.py,, 

_json_file_addr = "<AIRLEARNING_ROOT>\airlearning-ue4\Content\JsonFiles\EnvGenConfig.json”
game_file = "<AIRLEARNING_ROOT>\airlearning-ue4\AirLearning.uproject"
unreal_host_shared_dir = ""
unreal_exe_path = "C:\\Program Files\\Epic Games\\UE_4.18\\Engine\\Binaries\\Win64\\UE4Editor.exe"_

That was solved my problem.. Problem is may be i missunderstood about in the instruction written in "Step 3" following line . First i used like that"

json_file_addr = "<AIRLEARNING_ROOT>\Content\JsonFiles\EnvGenConfig"

Hope this one will help who facing problem like me~~~~
Thanks Sri for your kinding help~~~

**Comment by srivatsankrishnan** [comment]
I think this still can't be the issue you were running into. If your machine dependent settings file is incorrect or in your case the Json file path was incorrect, then training won't start. For instance the training script would have error'd out or the UE4 screen would have a prompt about Jsonfile being invalid. 

But I am Glad it is working at your end. I will close this issue for now. Feel free to re-open this if you run into it again.

**Comment by charlo1998** [comment]
Hi, i'm having a similar issue: i'm able to connect, but the training won't start and I get a NotImplementedError. am I supposed to implement the step, reset etc. methods myself?



(workspace) C:\Users\charl\workspace\airlearning\airlearning-rl\run_time>python collect_data.py
Using TensorFlow backend.
C:\Users\charl\workspace\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\charl\workspace\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\charl\workspace\lib\site-packages\tensorflow\python\framework\dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\charl\workspace\lib\site-packages\tensorflow\python\framework\dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\charl\workspace\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\charl\workspace\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tornado.general:Connect error on fd 4344: WSAECONNREFUSED
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

2022-05-13 10:06:15.588240: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2022-05-13 10:06:15.674282: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties:
name: NVIDIA GeForce RTX 2060 major: 7 minor: 5 memoryClockRate(GHz): 1.2
pciBusID: 0000:01:00.0
totalMemory: 6.00GiB freeMemory: 5.02GiB
2022-05-13 10:06:15.674451: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2022-05-13 10:06:16.075145: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-13 10:06:16.075245: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
2022-05-13 10:06:16.076013: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
2022-05-13 10:06:16.076385: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3686 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

2022-05-13 10:06:16.299001: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2022-05-13 10:06:16.299178: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-13 10:06:16.300228: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0
2022-05-13 10:06:16.302869: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N
2022-05-13 10:06:16.303480: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3686 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "collect_data.py", line 104, in <module>
    main()
  File "collect_data.py", line 100, in main
    runTask(task_el)
  File "collect_data.py", line 52, in runTask
    train_class.train(train_obj, env)
  File "C:\Users\charl\workspace\airlearning\airlearning-rl/algorithms/discrete/dqn\dqn_baselines.py", line 40, in train
    agent.learn(total_timesteps=settings.training_steps_cap)
  File "C:\Users\charl\workspace\airlearning\airlearning-rl\stable_baselines\deepq\dqn.py", line 170, in learn
    obs = self.env.reset()
  File "C:\Users\charl\workspace\airlearning\airlearning-rl\stable_baselines\common\base_class.py", line 523, in reset
    return self.venv.reset()[0]
  File "C:\Users\charl\workspace\airlearning\airlearning-rl\stable_baselines\common\vec_env\dummy_vec_env.py", line 45, in reset
    obs = self.envs[env_idx].reset()
  File "C:\Users\charl\workspace\lib\site-packages\gym\wrappers\order_enforcing.py", line 16, in reset
    return self.env.reset(**kwargs)
  File "C:\Users\charl\workspace\lib\site-packages\gym\core.py", line 74, in reset
    raise NotImplementedError
NotImplementedError
